### ISSUE TITLE
it does not seem to be working for me.

### ISSUE THREAD

**Issue by leoheck** [kantlivelong/OctoPrint-SmartPreheat#11]
Hi, it does not seem to be working for me.
I installed the plugin, but the graph looks pretty standard.

Should I configure the plugin before? Or it is ready for use?

![image](https://user-images.githubusercontent.com/1277920/82492483-a91cfd80-9abc-11ea-8669-a29ffaa50e9a.png)

**Comment by kantlivelong** [comment]
You clearly didn't read [this](https://raw.githubusercontent.com/kantlivelong/OctoPrint-SmartPreheat/master/.github/ISSUE_TEMPLATE.md).

However [this](https://community.octoprint.org/t/smartpreheat-not-preheating-both/19476/16) may help you. If not then please do the needful.

**Comment by leoheck** [comment]
Of course I didn't read a bunch of unecessary text. I am not demaning a fix. I am given you my feedback. But I agree with you, I will do the needful by uninstalling this.
