### ISSUE TITLE
Can't save when using Python3 pip

### ISSUE THREAD

**Issue by NovaViper** [kantlivelong/OctoPrint-SmartPreheat#13]
#### What were you doing?
I converted my Octoprint instance to use python3 instead of python2 using this [script](https://github.com/cp2004/Octoprint-Upgrade-To-Py3) to run a particular plugin that only functions on Python 3. However since doing so, the Smart PreHeat plugin does not save my changes at all. 

1. Run this [script](https://github.com/cp2004/Octoprint-Upgrade-To-Py3) to convert Octoprint from Python2 to Python3.
2. Change the script for Smart Preheat and save
3. Open up the Smart Preheat configurations and see that the changes did not save

#### What did you expect to happen?
Configurations to save

#### What happened instead?
It didn't save, and spot out this error
```
2020-07-11 05:08:30,455 - octoprint.server.api.settings - ERROR - Could not save settings for plugin Smart Preheat (0.0.4)
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/settings.py", line 580, in _saveSettings
    plugin.on_settings_save(data["plugins"][plugin_id])
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_smartpreheat/__init__.py", line 125, in on_settings_save
    if data.has_key("scripts_gcode_snippets_doSmartPreheat"):
AttributeError: 'dict' object has no attribute 'has_key'
```

#### Version of OctoPrint-SmartPreheat

0.0.4

#### Operating System running OctoPrint
OctoPi 0.17.0

#### Printer model & used firmware incl. version
Creality Ender 3, Marlin 2.0.5.4 bugfix

#### Link to octoprint.log with octoprnt.plugins.smartpreheat set to DEBUG
https://gist.github.com/NovaViper/59c35391f013139a1796fe2b4da760a4

**Comment by kantlivelong** [comment]
This is now fixed via d9c8c287b9fe95496e4056f2fbf0e69dbd97e814 and releases in 0.0.5.

Thanks for reporting with all the required information. :+1:
