### ISSUE TITLE
Remove line for preheat bed and wait until 80%

### ISSUE THREAD

**Issue by VirtualMike** [kantlivelong/OctoPrint-SmartPreheat#18]
#### What were you doing?

1. Install Smart Preheat
2. Go into the Smart Preheat
3. The initial block of code looks like this
4. Wait for bed to reach 80% of required temp then set to required temp
{% if printer_profile.heatedBed %}
M190 S{{ (plugins.smartpreheat.bed * 0.8)|round }}
M140 S{{ plugins.smartpreheat.bed }}
{% endif %}
5. Remove the M190 line and the preheat will work MUCH faster. It will start heating both the bed AND all tools at the same time instead of waiting for the bed to heat to 80%.
6. Better IMHO

#### Version of OctoPrint-SmartPreheat
(0.0.6)

#### Operating System running OctoPrint
Octoprint distro (raspian)
OctoPrint 1.4.1 Python 2.7.13 OctoPi 0.16.0

#### Printer model & used firmware incl. version
Ender 3 Pro with 4.2.7 board upgrade

#### Link to octoprint.log with octoprnt.plugins.smartpreheat set to DEBUG
![Screenshot 2021-06-12 205035](https://user-images.githubusercontent.com/5114955/121792205-f1272a80-cbbf-11eb-936d-04102a1e4047.png)

**Comment by beardedfool** [comment]
Just a comment. I think the dev has this right to make it applicable for as many users as possible....

Some larger devices (CR10) may take some time to spread the heat throughout the bed/ glass etc. 
i.e. temp read as thermistor isn't the temp at the print surface 

So no reason you can't remove for your case but suspect that was the intention behind the M190; but interested to see what they say.

**Comment by kantlivelong** [comment]
This is entirely environmental. The baseline gcode script provided is exactly just that, a baseline. No config will work for everyone. Given that you can certainly use and suggest your method to others but it's not something I'm going to change.
