### ISSUE TITLE
When actual extruder temp order is upper target order, decrease it immediatly

### ISSUE THREAD

**Issue by Alcolo47** [kantlivelong/OctoPrint-SmartPreheat#20]
Concrete case:
With my Anycube cobra Neo, after "filament loading" the extruder temp order stay at 230.

When I start a print with extruder temp to 200, The plugin wait for bed intermediate temp before lowing extruder temp order.
But in this case is better to lowing extruder temp asap.

![image](https://github.com/kantlivelong/OctoPrint-SmartPreheat/assets/6816588/550cf3c8-b1b9-450c-88e0-4bf95802b9c5)

**Comment by kantlivelong** [comment]
You can edit the gcode script to do this unless I'm missing something here.

**Comment by Alcolo47** [comment]
In my example, you can see that I start printing with an hot tool (230).
I this case, don't wait for bed intermediate target, to decrease tool temp.

**Comment by kantlivelong** [comment]
Again, this can be done in the snippet. This is considered configuration.
